# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 3 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: install pnpm
      run: npm install -g pnpm
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    
    - name: pnpm install
      run: pnpm install

    - name: npm install ts-node
      run: npm install -g ts-node
      
    - name: Run main.ts with ts-node-esm
      run: ts-node-esm main.ts

    # - uses: stefanzweifel/git-auto-commit-action@v5
    #   with:
    #     commit_message: Auto Update Data
    #     create_branch: true
    #     branch: release
    #     add_options: '-f'
    #     file_pattern: 'data/'
    #     skip_dirty_check: true

    - name: Checkout release
      uses: actions/checkout@v4
      with:
        ref: release
        path: data

    - name: Git push assets to release branch
      run: |
        rm -r data/bangumi-data
        mkdir data/bangumi-data
        cp ./original-data/bangumi-data/data.d.ts ./data/bangumi-data/data.d.ts
        cp ./data.d.ts ./data
        cd data
        sed -i 's#./original-data/bangumi-data/data.d.ts#./bangumi-data/data.d.ts#' ./data.d.ts
        git checkout -b release
        git add .
        git commit -m "Auto Update Data"
        git push -f -u origin release
